num1 = int(input("Enter number 1: "))
num2 = int(input("Enter number 2: "))
print("Sum: ", num1 + num2)
print("Product: ", num1 * num2)
print("Exponentiation: ", num1 ** num2)
print("Modulus: ", num1 % num2)
print("Ratio: 1:", num2/num1 )
